apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulutbilisim
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bulutbilisim
  template:
    metadata:
      labels:
        app: bulutbilisim
    spec:
      containers:
        - name: bulutbilisim-container
          image: muhammedenessarica/bulutbilisimv1
          ports:
            - containerPort: 5000